id: PDF8ACC94
initial_creation_type: ocr
source_metadata:
  volumes:
    cd9fa02293b54bb4ae9f9110d4c28354:
      base_file: v046.txt
      image_group_id: I1PD95891
      title: བསྡུས་པའི་རིམ་པའི་བསྒྲུབ་ཐབས།
      total_pages: 1201
      volume_number: 46
